-- Users table seeds here (Example)
INSERT INTO users (name, email, password)
VALUES ('Nicole Dunn','quis@outlook.com','password'),
  ('Cole Monroe','proin.nisl.sem@google.edu','password'),
  ('Luke Gray','nunc.ullamcorper@outlook.net','password'),
  ('Orlando Ross','mauris@protonmail.edu','password'),
  ('Brady Mcmahon','elit.etiam.laoreet@yahoo.org','password'),
  ('Danielle Harvey','ligula.donec@google.ca','password'),
  ('Vivian Chambers','lorem@icloud.net','password'),
  ('Fuller Gross','vel.arcu@protonmail.ca','password'),
  ('Macaulay Cooke','in.sodales.elit@yahoo.com','password'),
  ('Summer Rogers','nec@aol.couk','password'),
  ('Stone Ross','cursus.et@aol.couk','password'),
  ('Hedy Kelly','laoreet@google.com','password'),
  ('Odette Wall','amet.risus.donec@protonmail.net','password'),
  ('Walker Thornton','nulla.cras@aol.org','password'),
  ('Wendy Ortiz','velit.dui@protonmail.ca','password'),
  ('Ishmael Merrill','urna.nec.luctus@aol.com','password'),
  ('Brooke Russo','orci@protonmail.edu','password'),
  ('Damian Rogers','pede@hotmail.org','password'),
  ('Leonard Leonard','elit@google.couk','password'),
  ('Grady Walton','cubilia.curae@outlook.org','password');
