-- Widgets table seeds here (Example)
INSERT INTO comments (user_id, post_id, comment, created_at)
VALUES (11,22,"I disagree"),
  (15,21,"What a nice source"),
  (17,13,"I don't get it"),
  (8,9,"This ^"),
  (13,18,"Thanks for the resource UwU"),
  (5,17,"This is also a pretty good resource https://youtu.be/dQw4w9WgXcQ"),
  (15,15,"I disagree"),
  (8,5,"What a nice source"),
  (6,8,"I don't get it"),
  (11,28,"This ^"),
  (6,5,"Thanks for the resource UwU"),
  (5,12,"This is also a pretty good resource https://youtu.be/dQw4w9WgXcQ"),
  (14,29,"I disagree"),
  (15,4,"What a nice source"),
  (12,24,"I don't get it"),
  (12,11,"This ^"),
  (11,11,"Thanks for the resource UwU"),
  (14,21,"This is also a pretty good resource https://youtu.be/dQw4w9WgXcQ"),
  (3,18,"I disagree"),
  (13,24,"What a nice source"),
  (7,5,"I don't get it"),
  (3,4,"This ^"),
  (2,11,"Thanks for the resource UwU"),
  (16,21,"This is also a pretty good resource https://youtu.be/dQw4w9WgXcQ"),
  (7,2,"I disagree"),
  (17,6,"What a nice source"),
  (8,25,"I don't get it"),
  (3,6,"This ^"),
  (16,5,"Thanks for the resource UwU"),
  (13,3,"This is also a pretty good resource https://youtu.be/dQw4w9WgXcQ");
