DROP TABLE if EXISTS ratings CASCADE;

CREATE TABLE post_ratings (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  rating SMALLINT
)
