DROP TABLE if EXISTS liked_pins CASCADE;

CREATE TABLE liked_pins (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  post_id INTEGER REFERENCES pins(id) ON DELETE CASCADE
);
